appenders:
  stdout:
    kind: console
    encoder:
      pattern: "[{d(%Y-%m-%d %H:%M:%S)}] {({l}):5.5} {m}{n}"
  fileout:
    kind: file
    path: log/.log
    append: false
    encoder:
      pattern: "[{d(%Y-%m-%d %H:%M:%S)}] {({l}):5.5} {f}:{L} {m}{n}"
root:
  level: info
  appenders:
  - stdout
  - fileout
